### PR TITLE
SpritePatcherUpdate 

### PR DESCRIPTION
**Pull request by PrimeSonic**
- Updates `SpritePatcher` to work with the now atlas focused **SpriteManager** changes
- Relevant changes are currently on Subnautica Experimental
  - Should not be released until after these changes go to Subnautica's Stable branch
- Removes `AddSprite` method from `SpritePatcher`,  
updating `PingTypePatcher` to queue up its sprite like everything else

### CODE REVIEW

**Comment by tobeyStraitjacket** [comment]
Just to clarify: Is this still a draft?

**Comment by PrimeSonic** [comment]
> Just to clarify: Is this still a draft?
These changes are for the Experimental branch, which I've forgotten if we are targeting as part of the next release.

**Comment by tobeyStraitjacket** [comment]
> > Just to clarify: Is this still a draft?
> > These changes are for the Experimental branch, which I've forgotten if we are targeting as part of the next release.

Gotcha. I know @MrPurple6411 [opened a branch for BZ experimental](https://github.com/SubnauticaModding/SMLHelper/tree/BelowZero-Unity-2019-4-2) since they changed to Unity 2019.4.2 etc., you may want to target that branch rather than devQ2? Then when it goes stable we can merge that branch into whatever dev branch we have going at the time to eventually release.

That being said, I'm not arbitrator of this repo, this is just suggestion and idk if it's best practice for this kind of situation :D

**Comment by tobeyStraitjacket** [comment]
> > > Just to clarify: Is this still a draft?
> > > These changes are for the Experimental branch, which I've forgotten if we are targeting as part of the next release.
> 
> Gotcha. I know @MrPurple6411 [opened a branch for BZ experimental](https://github.com/SubnauticaModding/SMLHelper/tree/BelowZero-Unity-2019-4-2) since they changed to Unity 2019.4.2 etc., you may want to target that branch rather than devQ2? Then when it goes stable we can merge that branch into whatever dev branch we have going at the time to eventually release.
> 
> That being said, I'm not arbitrator of this repo, this is just suggestion and idk if it's best practice for this kind of situation :D

Oh wait, this is for SN experimental. Hmm yeah nvm then.

**Pull request merged**
